#!/bin/bash
if [ -z "$SUDO_COMMAND" ]   # Need to run this with sudo 
then 
   mntusr=$(id -u) grpusr=$(id -g) sudo $0 $* 
   exit 0 
fi 
cd `dirname $0`
rm rhstudio.dmg
gunzip < rhstudio.dmg.gz > rhstudio.dmg
if [ ! -d /mnt/dmg ]; then mkdir /mnt/dmg; fi
mount -o loop -t hfsplus rhstudio.dmg /mnt/dmg/
cp -r ${HOME}/export/opensource/macosx.carbon.x86/rhstudio /mnt/dmg/rhstudio.app/
umount /mnt/dmg
